"""add_currency_to_expenses

Revision ID: f04fa9f5c2f7
Revises: 
Create Date: 2025-10-30 01:14:10.583928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04fa9f5c2f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('expenses', sa.Column('currency', sa.String(length=3), nullable=True))
    # Set default value 'EUR' for all existing expenses
    op.execute("UPDATE expenses SET currency = 'EUR' WHERE currency IS NULL")
    # Now make it non-nullable with default
    op.alter_column('expenses', 'currency',
                    nullable=False,
                    server_default='EUR')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
